services:
  - type: web
    runtime: image
    name: albyhub
    image:
      url: ghcr.io/getalby/hub:latest
    numInstances: 1
    region: frankfurt
    plan: free
    autoDeploy: false
    envVars:
      - key: WORK_DIR
        value: /data/albyhub
      - key: LDK_ESPLORA_SERVER
        value: "https://electrs.getalbypro.com"
